// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "c2081d42-fb8d-274f-a923-19cc7b23652d");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1594633419);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1594503411);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1594503395);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1594633392);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1594503531);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1594633539);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1594503441);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 5707);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1594503381);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{58ef8d4a-f89a-7745-a260-a8ceefdc79f3}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1594633397653");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1594635192653");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1594633398258");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1594636998258");
user_pref("browser.search.region", "NL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200708170202");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1594633392");
user_pref("browser.slowStartup.averageTime", 2517);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200708170202");
user_pref("browser.startup.homepage_override.mstone", "78.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1594633390);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"jid1-zadieub7xozojw_jetpack-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"jid1-zadieub7xozojw_jetpack-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1594503388881");
user_pref("devtools.aboutdebugging.collapsibilities.processes", false);
user_pref("devtools.aboutdebugging.tmpExtDirPath", "/Users/harmtemolder/GitHub/buster/src");
user_pref("distribution.iniFile.exists.appversion", "78.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "4d5fa9e2c7b040f5988d3c8bf911bfbe");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200708170202");
user_pref("extensions.lastAppVersion", "78.0.2");
user_pref("extensions.lastPlatformVersion", "78.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.recommendations.hideNotice", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-ZAdIEUB7XOzOJw@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{e58d3966-3d76-4cd9-8552-1582fbc800c1}", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"989a7bfa-0e97-6c4c-ae74-7c51d72e65ca\",\"formautofill@mozilla.org\":\"5a37d299-c1ec-5040-85da-75af79a3b321\",\"screenshots@mozilla.org\":\"09ead9b4-f827-6542-84d8-6d7b10951fc8\",\"webcompat-reporter@mozilla.org\":\"45f46026-006f-a048-bc23-a6752e9e89d1\",\"webcompat@mozilla.org\":\"22fe219e-88d9-9c41-be5f-0e399f38b786\",\"default-theme@mozilla.org\":\"6a8e91f2-a14c-374c-bfcf-8d216bf7bfd3\",\"google@search.mozilla.org\":\"cd5fb3da-98a5-3f45-8b3e-8efc90049377\",\"bing@search.mozilla.org\":\"cf5d1e1c-399c-834b-af4c-344639085f76\",\"amazon@search.mozilla.org\":\"57cbfa67-8c53-5046-a345-0da4e5ef429b\",\"chambers-en-GB@search.mozilla.org\":\"af31af15-e43d-2947-a921-aeb05fe1904e\",\"ddg@search.mozilla.org\":\"17caebd2-7011-2840-bd2a-96414efb1102\",\"ebay@search.mozilla.org\":\"def817bb-f3db-9545-b09f-ba457b5f2e59\",\"wikipedia@search.mozilla.org\":\"1aeb5187-b348-f24b-9638-1491171fd3a3\",\"jid1-ZAdIEUB7XOzOJw@jetpack\":\"4f976480-2136-6a41-96da-f4310e47160c\",\"{e58d3966-3d76-4cd9-8552-1582fbc800c1}\":\"468b3369-77f6-8742-9fe1-2acd52d6efbb\"}");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c4778c42-9355-3e43-a367-adb42703f26a");
user_pref("security.sandbox.plugin.tempDirSuffix", "6399519c-68b7-9740-bbb9-3b5851e0841c");
user_pref("services.blocklist.addons.checked", 1594633539);
user_pref("services.blocklist.gfx.checked", 1594633539);
user_pref("services.blocklist.plugins.checked", 1594633539);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1594627700193\"");
user_pref("services.settings.last_update_seconds", 1594633539);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1594633539);
user_pref("services.settings.main.cfr-fxa.last_check", 1594633539);
user_pref("services.settings.main.cfr.last_check", 1594633539);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1594633539);
user_pref("services.settings.main.hijack-blocklists.last_check", 1594633539);
user_pref("services.settings.main.language-dictionaries.last_check", 1594633539);
user_pref("services.settings.main.messaging-experiments.last_check", 1594633539);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1594633539);
user_pref("services.settings.main.search-config.last_check", 1594633539);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1594633539);
user_pref("services.settings.main.sites-classification.last_check", 1594633539);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1594633539);
user_pref("services.settings.main.whats-new-panel.last_check", 1594633539);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1594633388);
user_pref("toolkit.telemetry.cachedClientID", "67e82fc4-175e-9541-97b1-eed6c411f3bc");
user_pref("toolkit.telemetry.previousBuildID", "20200708170202");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
